name: ci

on:
  push:
    branches:
      - "master"
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Setup GitHub user
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "GitHub Actions"

      - name: Install deps
        run: npm ci
      
      - name: Build
        run: npm run build

      - name: Run lint
        run: npm run lint

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
